### ISSUE TITLE
Bug on layout in view field

### ISSUE THREAD

**Issue by ryanmitchell** [optimistdigital/nova-simple-repeatable#19] opened 2021-09-16 10:25 UTC
<img width="847" alt="Screenshot 2021-09-16 at 11 22 39" src="https://user-images.githubusercontent.com/51899/133596018-6c1b7377-9cfd-4e7e-8288-ff58c8b9fac5.png">

The view layout seems to be getting styles from the edit layout (`.simple-repeatable>:nth-child(2)`) which is making it ignore the width and throw off the layout compared to fields around it.

**Comment by Tarpsvo** [comment] 2021-10-01 12:54
Hi! Thank you for the report. The issue is now fixed in version 1.4.1. :)

**Closed by Tarpsvo** 2021-10-01 12:54 UTC
